In [39]:
import numpy as np
a= np.array([1,2,3,4])
print(a)

[1 2 3 4]


How would I multiple two large arrays without vectorization?

In [52]:
import time
a = np.random.rand(1000000)
b = np.random.rand(1000000)
for i in range(1,10):
    print(a[i])
c = 0
tic = time.time()
for i in range(1000000):
    c+=a[i]*b[i]
toc = time.time()
time1= 1000*(toc-tic)
print(toc)
print(tic)
print("Regular version took:" + str(time1) + " miliseconds")
print(c)

0.9483418486074625
0.3763063533725667
0.09795264844968632
0.18736512238805914
0.8129289808784267
0.14126977557579257
0.9898191965651315
0.9644591305680643
0.29450524142021306
1598789850.6036477
1598789850.0185645
Regular version took:585.0832462310791 miliseconds
250449.2907371167


This is the Vectorized version of this code. Uses something called, "SIMD: short for Single Instruction/Multiple Data"

In [48]:
tic = time.time()
c = np.dot(a,b)
toc = time.time()
time2= 1000*(toc-tic)
print("Vectorized version took:" + str(time2) + " miliseconds")
print(c)

Vectorized version took:0.9634494781494141 miliseconds
249937.7535876613


Another example with multiplying e^i 

In [57]:
a = np.random.rand(1000000)
tic = time.time()
u = np.exp(a)
#np.log exist, np.abs, np.maximum, np.minimum
toc = time.time()
time1= 1000*(toc-tic)
print("Vectorized version took:" + str(time1) + " miliseconds")
print(u)

Vectorized version took:11.004209518432617 miliseconds
[1.54076611 1.20149019 1.22703507 ... 2.35316107 2.59703723 2.10709449]


In [62]:
import math
a = np.random.rand(1000000)
tic = time.time()
u = np.zeros(1000000)
for i in range(1000000):
    u[i]=math.exp(a[i])
toc = time.time()
time2= 1000*(toc-tic)
print("Vectorized version took:" + str(time2) + " miliseconds")
print(u)

Vectorized version took:371.04153633117676 miliseconds
[1.02625432 1.89950836 1.95713477 ... 2.71791207 1.81099146 2.36716918]
